### ISSUE TITLE
feature: Interoperability with channel-typing

### ISSUE THREAD

**Issue by randomzigzag** [Algoinde/powercord-tile-channels#1]
I'm unsure on how this could be accomplished. ([Link to the plugin](https://github.com/powercord-community/channel-typing/))

**Comment by Algoinde** [comment]
Done, but this will work when [this](https://github.com/powercord-community/channel-typing/pull/7) is merged (or use my [fork](https://github.com/Algoinde/channel-typing/tree/patch-1) of channel-typing until then).

**Comment by Algoinde** [comment]
Merged and resolved.
