### ISSUE TITLE
Bug: text is cut out when using largest font size

### ISSUE THREAD

**Issue by freeman42x** [Algoinde/powercord-tile-channels#2]
![image](https://user-images.githubusercontent.com/1758708/111463933-d52efc80-8728-11eb-818c-46100a1e519e.png)

The right side of the channel names is being cut out on the largest font size set under Appearance -> Chat font scaling.

**Comment by Algoinde** [comment]
Would slightly reducing the font size for channels be a viable solution for you? Or you need them this big specifically?

Edit: Oh wait, I see now. The channels should not scale at all with that. I'll fix shortly.

**Comment by Algoinde** [comment]
This is now fixed!
